"""empty message

Revision ID: 62a865a92b47
Revises: 7b7f3ac61b5d
Create Date: 2023-07-13 19:08:58.383350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a865a92b47'
down_revision = '7b7f3ac61b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('user_last_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['lastname'])
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_last_name_key', ['last_name'])
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###
